"""add MessageReactionModel

Revision ID: 89ac2fcd84db
Revises: caf22645ac93
Create Date: 2026-02-21 08:09:28.467834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89ac2fcd84db"
down_revision: Union[str, Sequence[str], None] = "caf22645ac93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_reactions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("reaction", sa.String(length=32), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "message_id"),
    )
    op.alter_column("media_files", "author_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(
        op.f("media_files_author_id_fkey"), "media_files", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "media_files", "users", ["author_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column("messages", "author_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(op.f("messages_theme_id_fkey"), "messages", type_="foreignkey")
    op.drop_constraint(op.f("messages_section_id_fkey"), "messages", type_="foreignkey")
    op.drop_constraint(op.f("messages_author_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "users", ["author_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "messages", "themes", ["theme_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "messages", "sections", ["section_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(op.f("themes_author_id_fkey"), "themes", type_="foreignkey")
    op.create_foreign_key(
        None, "themes", "users", ["author_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "themes", type_="foreignkey")
    op.create_foreign_key(
        op.f("themes_author_id_fkey"),
        "themes",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_author_id_fkey"),
        "messages",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("messages_section_id_fkey"),
        "messages",
        "sections",
        ["section_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("messages_theme_id_fkey"),
        "messages",
        "themes",
        ["theme_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("messages", "author_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(None, "media_files", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_files_author_id_fkey"),
        "media_files",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("media_files", "author_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table("message_reactions")
    # ### end Alembic commands ###
