"""add MediaFileMode, MessageMediaFileModel

Revision ID: caf22645ac93
Revises: 36614b00bea7
Create Date: 2026-02-13 16:14:26.841860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "caf22645ac93"
down_revision: Union[str, Sequence[str], None] = "36614b00bea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_files",
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("extension", sa.String(length=50), nullable=False),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column(
            "is_temp", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_path"),
    )
    op.create_index(
        "ix_media_files_author_id", "media_files", ["author_id"], unique=False
    )
    op.create_index("ix_media_files_is_temp", "media_files", ["is_temp"], unique=False)
    op.create_table(
        "message_media_files",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("media_file_id", sa.UUID(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"], ["media_files.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "media_file_id"),
    )
    op.create_index(
        "ix_message_media_media_file_id",
        "message_media_files",
        ["media_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_media_message_id",
        "message_media_files",
        ["message_id"],
        unique=False,
    )
    op.drop_constraint(op.f("themes_parent_id_fkey"), "themes", type_="foreignkey")
    op.create_foreign_key(
        "themes_parent_id_fkey", "themes", "themes", ["parent_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("themes_parent_id_fkey", "themes", type_="foreignkey")
    op.create_foreign_key(
        op.f("themes_parent_id_fkey"),
        "themes",
        "themes",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_message_media_message_id", table_name="message_media_files")
    op.drop_index("ix_message_media_media_file_id", table_name="message_media_files")
    op.drop_table("message_media_files")
    op.drop_index("ix_media_files_is_temp", table_name="media_files")
    op.drop_index("ix_media_files_author_id", table_name="media_files")
    op.drop_table("media_files")
    # ### end Alembic commands ###
